import os

SYNTAX_FILE = os.path.sep.join(__file__.split(os.path.sep)[:-2]) + os.path.sep + 'syntax.pys.json'

TOKENS = {
    'EOF': ord('\0'),
    'KEYWORD': 1,
    'IDENTIFIER': 2,
    'NUMBER': 3,
    'STRING': 4,
    'PLUS': ord('+'),
    'MINUS': ord('-'),
    'MUL': ord('*'),
    'DIV': ord('/'),
    'FDIV': 5,
    'POW': 6,
    'MOD': ord('%'),
    'AND': 7,
    'OR': 8,
    'XOR': ord('^'),
    'NOT': ord('~'),
    'LSHIFT': 9,
    'RSHIFT': 11,
    'IPLUS': -ord('+'),
    'IMINUS': -ord('-'),
    'IMUL': -ord('*'),
    'IDIV': -ord('/'),
    'IFDIV': 12,
    'IPOW': 13,
    'IMOD': -ord('%'),
    'IAND': 14,
    'IOR': 15,
    'IXOR': -ord('^'),
    'ILSHIFT': 16,
    'IRSHIFT': 17,
    'INCREMENT': 18,
    'DECREMENT': 19,
    'COLON': ord(':'),
    'QUESTION': ord('?'),
    'EQ': ord('='),
    'LPAREN': ord('('),
    'RPAREN': ord(')'),
    'LSQUARE': ord('['),
    'RSQUARE': ord(']'),
    'LBRACE': ord('{'),
    'RBRACE': ord('}'),
    'EE': 20,
    'CE': -ord('~'),
    'NE': 21,
    'LT': ord('<'),
    'GT': ord('>'),
    'LTE': 22,
    'GTE': 23,
    'NEWLINE': ord('\n'),
    'COMMA': ord(','),
    'DOT': ord('.'),
    'SEMICOLON': ord(';')
}

DEFAULT_SYNTAX = {
    'keywords': {
        'and': 'and',
        'break': 'break',
        'case': 'case',
        'catch': 'catch',
        'continue': 'continue',
        'default': 'default',
        'del': 'del',
        'elif': 'elif',
        'else': 'else',
        'for': 'for',
        'func': 'func',
        'if': 'if',
        'in': 'in',
        'is': 'is',
        'not': 'not',
        'of': 'of',
        'or': 'or',
        'return': 'return',
        'switch': 'switch',
        'throw': 'throw',
        'try': 'try',
        'while': 'while'
    },
    'builtins': {}
}